export const INTERESTS_LIST = [
  "USMLE Step 1",
  "USMLE Step 2 CK",
  "USMLE Step 3",
  "PLAB 1",
  "PLAB 2",
  "FCPS Part 1",
  "FCPS Part 2",
  "Cardiology",
  "Neurology",
  "Respiratory",
  "Gastroenterology",
  "Endocrinology",
  "Nephrology",
  "Hematology",
  "Infectious Diseases",
  "Rheumatology",
  "Dermatology",
  "Psychiatry",
  "Pathology",
  "Pharmacology",
  "Physiology",
  "Biochemistry",
  "Microbiology",
  "Immunology",
  "Anatomy",
];

export const DISEASES = [
  "Sorethroat/Respiratory tract infections",
  "Musculoskeletal pain",
  "Malaria",
  "Dengue",
  "Hypertension",
  "Diarrhoea",
  "Diabetes",
  "Kidney stones",
  "Cholecystitis",
  "Appendicitis",
  "Gestational hemorrhage",
  "Hemorrhagic stroke",
  "Ischemic stroke",
  "Myocardial Infarction",
];

export const MAX_QUESTIONS = 5;
